server:
  port: 8084
spring:
  application:
    name: sparql-explorer-service
sparql:
  endpoint: ${SPARQL_ENDPOINT:http://localhost:3030/lod/sparql}
management:
  endpoints:
    web:
      exposure:
        include: health,info
