PREFIX lod:     <https://data.lod-school.ma/ontology#>
PREFIX schema:  <https://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>

CONSTRUCT {
    ?etudiant lod:matchesOffer ?offre .
    ?etudiant dcterms:identifier ?id .
    ?offre schema:title ?titre .
    ?offre lod:postedBy ?comp .
    ?comp schema:name ?entreprise .
}
WHERE {
    ?etudiant a lod:Student ;
              dcterms:identifier ?id ;
              lod:hasSkill ?skill .
    ?offre a lod:InternshipOffer ;
           schema:title ?titre ;
           lod:requiresSkill ?skill ;
           lod:postedBy ?comp ;
           lod:status "Ouverte"@fr .
    ?comp schema:name ?entreprise .
}
LIMIT 200
