PREFIX lod:    <https://data.lod-school.ma/ontology#>
PREFIX schema: <https://schema.org/>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

# C1 — CONSTRUCT profil étudiant (export RDF)
CONSTRUCT {
    ?etudiant a lod:Student ;
              lod:level ?niveau ;
              lod:enrolledIn ?prog ;
              schema:addressLocality ?ville ;
              lod:mention ?mention ;
              lod:hasSkill ?skill .
    ?prog rdfs:label ?filiere .
    ?skill skos:prefLabel ?competence .
}
WHERE {
    ?etudiant a lod:Student ;
              lod:level ?niveau ;
              lod:enrolledIn ?prog ;
              schema:addressLocality ?ville ;
              lod:mention ?mention ;
              lod:hasSkill ?skill .
    ?prog rdfs:label ?filiere .
    ?skill skos:prefLabel ?competence .
    FILTER (lang(?competence) = "fr")
}
LIMIT 50
