PREFIX lod:     <https://data.lod-school.ma/ontology#>
PREFIX schema:  <https://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?etudiant_id ?offre ?titre ?entreprise
       (COUNT(?skillCommun) AS ?nb_competences_communes)
WHERE {
    ?etudiant a lod:Student ;
              dcterms:identifier ?etudiant_id ;
              lod:hasSkill ?skillCommun .
    ?offre a lod:InternshipOffer ;
           schema:title ?titre ;
           lod:requiresSkill ?skillCommun ;
           lod:postedBy ?comp ;
           lod:status "Ouverte"@fr .
    ?comp schema:name ?entreprise .
}
GROUP BY ?etudiant_id ?offre ?titre ?entreprise
ORDER BY DESC(?nb_competences_communes)
LIMIT 20
