apiVersion: v1
kind: ConfigMap
metadata:
  name: gradify-config
  namespace: gradify
data:
  SPARQL_ENDPOINT: "http://fuseki:3030/lod/sparql"
  JWT_SECRET: "gradify-secret-key-change-in-production-2024"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin123"
  FUSEKI_ADMIN_PASSWORD: "admin123"
