server:
  port: 8083
spring:
  application:
    name: matching-service
sparql:
  endpoint: ${SPARQL_ENDPOINT:http://localhost:3030/lod/sparql}
management:
  endpoints:
    web:
      exposure:
        include: health,info
